# 对标 GoFrame config.yaml
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    host: "9.134.232.197"
    port: 3306
    user: "root"
    password: "lsj@24625"
    database: "todo_db"
