# 对标 GoFrame config.yaml
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level: "all"
  stdout: true

database:
  default:
    host: "数据库地址"
    port: 3306
    user: "用户名"
    password: "密码"
    database: "todo_db"
